# Generated by Django 4.0.4 on 2022-05-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('Part-Time', 'Part.Time'), ('Full-Time', 'Full.Time')], max_length=11),
        ),
    ]
