# Generated by Django 4.0.4 on 2022-05-28 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_tracking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracking',
            new_name='TrackingDetections',
        ),
    ]
