# Generated by Django 4.0.4 on 2022-05-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('file', models.CharField(max_length=120)),
                ('mark', models.CharField(default='Not marked', max_length=20)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
    ]
