# Generated by Django 4.0.4 on 2022-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_alter_detections_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='mark',
            field=models.CharField(choices=[('Not marked', 'isNotMarked'), ('Danger', 'isDanger'), ('Safe', 'isSafe')], default='Not marked', max_length=20),
        ),
    ]
