# Generated by Django 4.0.4 on 2022-05-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('plate', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
    ]
